[menu-bar] Migrate FilePicker to Expo Modules
expo/orbit pull request #132
Opened 2024-01-09 21:51 UTC by gabrieldonadel

# Why

Now that expo modules supports macOS, we can start to slowly migrate our modules to use the Sweet API

# How

Migrate FilePicker to use Expo Modules

# Test Plan

https://github.com/expo/orbit/assets/11707729/3ae9d671-97a7-4cdb-9bba-04061b7196d3

2024-01-09 22:14 UTC, alanjhughes requested changes
Great! I'll start helping out with this. Just a few comments

2024-01-09 22:14 UTC, alanjhughes commented on apps/menu-bar/modules/file-picker/ios/FilePickerModule.swift
> +        }
```suggestion
        AsyncFunction("pickFileWithFilenameExtension"){  (filenameExtensions: [String], prompt: String) in
              NSApp.activate(ignoringOtherApps: true)
              let panel = NSOpenPanel()

              if !prompt.isEmpty {
                  panel.prompt = prompt
              }

              panel.allowsMultipleSelection = false
              panel.canChooseDirectories = true
              panel.canCreateDirectories = true

              if #available(macOS 11.0, *) {
                  var allowedTypes = [UTType]()

                  for extensionString in filenameExtensions {
                      let utTypesFromTag = UTType.types(tag: extensionString, tagClass: .filenameExtension, conformingTo: nil)
                      if !utTypesFromTag.isEmpty {
                          allowedTypes += utTypesFromTag
                      }


                      if let utTypeFromFilenameExtension = UTType(filenameExtension: extensionString), !allowedTypes.contains(utTypeFromFilenameExtension) {
                          allowedTypes.append(utTypeFromFilenameExtension)
                      }
                  } 

                  panel.allowedContentTypes = allowedTypes
              }

              guard panel.runModal() == NSApplication.ModalResponse.OK else {
                   throw Exception(name: "FILE_PICKER_ERROR", description: "NSModalResponseCancel")
              } 
              return panel.url?.path
        }.runOnQueue(.main)
```
We should just be able to run this on the main queue and remove the `Promise` parameter

2024-01-09 22:14 UTC, alanjhughes commented on apps/menu-bar/modules/file-picker/ios/FilePickerModule.swift
> +        }
Same as above.

2024-01-10 09:06 UTC, tsapeta commented on apps/menu-bar/modules/file-picker/ios/FilePickerModule.swift
> +            DispatchQueue.main.async {
Sooo many spaces 🙉

2024-01-10 14:56 UTC, alanjhughes approved these changes

2024-01-10 19:14 UTC, tsapeta approved these changes

2024-01-18 15:25 UTC, merged